[package]
name = "wasmjvm_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasmjvm_class = { path = "../class", version = "0.1.0" }
wasmjvm_common = { path = "../common", version = "0.1.0" }
